### ISSUE TITLE
Gem-ified doesn't work

### ISSUE THREAD

**Issue by ssfsx17** [vmware-archive/salty-vagrant#6] opened 2012-07-18 17:02 UTC
I am using a Windows system.

I installed salty-vagrant as:
gem install vagrant-salt

I installed Vagrant both from the Windows installer and as a gem

I tried to run the example:

C:\workspace\salty-vagrant\example>vagrant up
C:/usr/vagrant/vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- vagrant-salt/provisioner (LoadError)
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
        from C:/workspace/salty-vagrant/lib/vagrant-salt.rb:2:in `<top (required)>'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/workspace/salty-vagrant/example/Vagrantfile:1:in`<top (required)>'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:115:in `load'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:115:in`block in procs_for_source'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config.rb:41:in `block in capture_configures'
        from <internal:prelude>:10:in`synchronize'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config.rb:36:in `capture_configures'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:114:in`procs_for_source'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:51:in `block in set'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:45:in`each'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:45:in `set'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/environment.rb:377:in`block in load_config!'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/environment.rb:392:in `call'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/environment.rb:392:in`load_config!'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/environment.rb:327:in `load!'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/bin/vagrant:40:in`<top (required)>'
        from C:/usr/vagrant/vagrant/bin//../embedded/bin/vagrant:19:in `load'
        from C:/usr/vagrant/vagrant/bin//../embedded/bin/vagrant:19:in`<main>'

**Comment by akoumjian** [comment] 2012-07-18 17:11
1. What does your Vagrantfile look like?
2. From a Ruby shell (irb), can you `require 'vagrant-salt'`

**Comment by ssfsx17** [comment] 2012-07-18 17:15
My Vagrantfile is the example one from source. (I know this will fail on the Salt highstate execution, but that's not the problem here)

I discovered that my Windows installation of Vagrant has its own repo of gems, separate from any other Ruby installation. Therefore, I have now tried:
- vagrant gem install vagrant-salt

But this fails due to needing the development tools installed.

(I don't have a Ruby shell available right now)

**Comment by akoumjian** [comment] 2012-07-18 17:18
The example Vagrantfile has `require "../lib/vagrant-salt"` as the first line. You should remove this if you are using it as a gem. 

As far as separate gems for the vagrant install, I cannot help with that as my understanding of how it works is very poor. On OS X it works when installed as a system-wide gem.

**Comment by ssfsx17** [comment] 2012-07-18 17:30
I tried changing the Vagrant file to this:

``` ruby
require "../lib/vagrant-salt/provisioner"

Vagrant::Config.run do |config|
  config.vm.box = "precise64"
  ## Use all the defaults:
  config.vm.provision VagrantSalt do |salt|
    salt.run_highstate = true
  end
end
```

But now I get a different stacktrace:
    C:\workspace\salty-vagrant\example>vagrant up
    C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/vm/provisioner.rb:26:in `configure': undefined method`config_class' for VagrantSalt:Module (NoMethodError)
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/vm/provisioner.rb:21:in `initialize'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/vm.rb:71:in`new'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/vm.rb:71:in `provision'
        from C:/workspace/salty-vagrant/example/Vagrantfile:6:in`block in <top(required)>'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:83:in `call'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:83:in`block (2 levels) in load'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:79:in `each'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:79:in`block in load'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:76:in `each'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:76:in`load'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/environment.rb:387:in `block in load_config!'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/environment.rb:392:in`call'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/environment.rb:392:in `load_config!'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/environment.rb:327:in`load!'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/bin/vagrant:40:in `<top (required)>'
        from C:/usr/vagrant/vagrant/bin//../embedded/bin/vagrant:19:in`load'
        from C:/usr/vagrant/vagrant/bin//../embedded/bin/vagrant:19:in `<main>'

This suggests to me that the provisioner no longer works by itself.

**Comment by akoumjian** [comment] 2012-07-18 17:33
Try it like this:

``` ruby
Vagrant::Config.run do |config|
  config.vm.box = "precise64"
  ## Use all the defaults:
  config.vm.provision :salt do |salt|
    salt.run_highstate = true

    ## Optional Settings:
    # salt.minion_config = "salt/minion.conf"

    ## Only Use these with a masterless setup to
    ## load your state tree:
    # salt.salt_file_root_path = "salt/roots/salt"
    # salt.salt_pillar_root_path = "salt/roots/pillar"

    ## If you have a remote master setup, you can add
    ## your preseeded minion key
    # salt.master = true
    # salt.minion_key = "salt/key/testing.pem"
    # salt.minion_pub = "salt/key/testing.pub"
  end
end
```

Basically, remove the "require" since you are using the gem, not requiring a relative file.

**Comment by akoumjian** [comment] 2012-07-18 17:34
Also, did you actually try this?

> 1. From a Ruby shell (irb), can you require 'vagrant-salt'

**Comment by ssfsx17** [comment] 2012-07-18 17:38
I do not have a Ruby shell currently available to me. One thing I can try later on is to completely uninstall Vagrant, then install Ruby and only use Vagrant as a Ruby gem (which, by the way, I heard was planned to be deprecated in favor of making Vagrant as stand-alone as possible).

I am well aware that running Vagrant with vagrant-salt as a gem leads to not needing a "require" statement, but I want to make absolutely sure that I have exhausted every possible problem before I resort to installing Vagrant as a Ruby gem rather than as a standalone application.

(I'm an obsessive-compulsive build & release engineer, it's in my genes to think this way)

**Comment by akoumjian** [comment] 2012-07-18 17:41
I think you are confused. Vagrant does not need to be installed as a Ruby gem in order for it to use salt-vagrant as a gem. 

The first error you were getting was because you were trying to require a file which did not exist, namely a file located at `../lib/vagrant-salt/provisioner` which is under a lib directory, under the parent of the current working directory.

**Comment by ssfsx17** [comment] 2012-07-18 17:49
Alright, let's be clear about which stacktrace happens under which situation.

When my vagrantfile is this:

``` ruby
require "../lib/vagrant-salt"

Vagrant::Config.run do |config|
  config.vm.box = "precise64"
  ## Use all the defaults:
  config.vm.provision VagrantSalt do |salt|
    salt.run_highstate = true
  end
end
```

My stacktrace is this:
C:\workspace\salty-vagrant\example>vagrant up
C:/usr/vagrant/vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- vagrant-salt/provisioner (LoadError)
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
        from C:/workspace/salty-vagrant/lib/vagrant-salt.rb:2:in `<top (required)>'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/workspace/salty-vagrant/example/Vagrantfile:1:in`<top (required)>'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:115:in `load'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:115:in`block in procs_for_source'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config.rb:41:in `block in capture_configures'
        from <internal:prelude>:10:in`synchronize'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config.rb:36:in `capture_configures'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:114:in`procs_for_source'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:51:in `block in set'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:45:in`each'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:45:in `set'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/environment.rb:377:in`block in load_config!'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/environment.rb:392:in `call'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/environment.rb:392:in`load_config!'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/environment.rb:327:in `load!'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/bin/vagrant:40:in`<top (required)>'
        from C:/usr/vagrant/vagrant/bin//../embedded/bin/vagrant:19:in `load'
        from C:/usr/vagrant/vagrant/bin//../embedded/bin/vagrant:19:in`<main>'

The first lines of this stacktrace suggest that ../lib/vagrant-salt is being found but there is an error relating to ../lib/vagrant-salt/provisioner because ../lib/vagrant-salt.rb requires ../lib/vagrant-salt/provisioner.rb

Now, when my Vagrantfile is this:

``` ruby
require "../lib/vagrant-salt/provisioner"

Vagrant::Config.run do |config|
  config.vm.box = "precise64"
  ## Use all the defaults:
  config.vm.provision VagrantSalt do |salt|
    salt.run_highstate = true
  end
end
```

My stacktrace is this:
C:\workspace\salty-vagrant\example>vagrant up
C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/vm/provisioner.rb:26:in `configure': undefined method`config_class' for VagrantSalt:Module (NoMethodError)
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/vm/provisioner.rb:21:in `initialize'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/vm.rb:71:in`new'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/vm.rb:71:in `provision'
        from C:/workspace/salty-vagrant/example/Vagrantfile:6:in`block in <top(required)>'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:83:in `call'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:83:in`block (2 levels) in load'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:79:in `each'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:79:in`block in load'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:76:in `each'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:76:in`load'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/environment.rb:387:in `block in load_config!'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/environment.rb:392:in`call'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/environment.rb:392:in `load_config!'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/environment.rb:327:in`load!'
        from C:/usr/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/bin/vagrant:40:in `<top (required)>'
        from C:/usr/vagrant/vagrant/bin//../embedded/bin/vagrant:19:in`load'
        from C:/usr/vagrant/vagrant/bin//../embedded/bin/vagrant:19:in `<main>'

This stacktrace suggestions that ../lib/vagrant-salt/provisioner is being found, and that there is an attempt to parse ../lib/vagrant-salt/provisioner.rb

**Comment by ssfsx17** [comment] 2012-07-18 17:51
Also - it is true that Vagrant should not need to be, itself, a gem in order for vagrant-salt to be used as a gem. HOWEVER, I cannot install vagrant-salt as a gem itself into Vagrant's isolated gems, because Vagrant's isolated Ruby installation does not have the Ruby development tools. So my choices are as follows:
1. Focus on the "pure Ruby" way to do it. (I will try this later)
2. Focus on the "pure Vagrant" way to do it. (I am currently working on this)

**Comment by ssfsx17** [comment] 2012-07-18 18:00
I now believe this is an issue with Vagrant plugins on Windows installations in general, so feel free to close the issue.

**Comment by akoumjian** [comment] 2012-07-18 18:02
I will close it only because I do not have a windows env to reproduce. Ruby/Python loading on Windows is always such a pain. Please come back and post your solution if you do figure it out.

Sorry I could not be more help.

**Closed as completed by akoumjian** 2012-07-18 18:02 UTC
