### ISSUE TITLE
salt-call state.highstate -l debug not running

### ISSUE THREAD

**Issue by vinitkhandagle** [vmware-archive/salty-vagrant#77] opened 2013-05-14 13:10 UTC
Hello,
I am using salt plugin with vagrant. The sls files are completing with the installation of the packages. but after the run. salt tries to run the high.state with the debug option on the vm and fails. Looks to be that this run should have sudo prepended to it in the bootstrap_sh script. but that just my assumption as I am a novice on this. 
I am not sure if I am heading in the right direction. 

https://gist.github.com/vinitkhandagle/5575699

linbynd:=> {master} ~/vagrant_machines$ vagrant -v
Vagrant version 1.2.2
linbynd:=> {master} ~/vagrant_machines$ vagrant plugin list
vagrant-ansible (0.0.5)
vagrant-salt (0.4.0)
vagrant-vbguest (0.8.0)
linbynd:=> {master} ~/vagrant_machines$

**Comment by akoumjian** [comment] 2013-05-14 13:49
Can you share your Vagrantfile as well, and your minion conf if you have one?

Normally it is the vagrant plugin which issues `sudo salt-call state.highstate`. I don't see the message that should be printed before hand, either, leading me to belong something else it calling it. See [here](https://github.com/saltstack/salty-vagrant/blob/develop/lib/vagrant-salt/provisioner.rb#L300) and [here](https://github.com/saltstack/salty-vagrant/blob/develop/lib/vagrant-salt/provisioner.rb#L310) for reference.

**Comment by vinitkhandagle** [comment] 2013-05-14 14:01
Vagrant File: http://pastebin.com/5YcUnKvw
Minon File: http://pastebin.com/ph1jbTG3

Yes: looks like from the code lines the sudo should be happening..

**Comment by akoumjian** [comment] 2013-05-14 14:10
Link to your vagrantfile is not correct.

**Comment by vinitkhandagle** [comment] 2013-05-14 14:26
Vagrant file : http://pastebin.com/hpSQ5Byp

sorry about that

**Comment by akoumjian** [comment] 2013-05-14 14:42
I believe the command is executing successfully, but is returning a non-zero exit code due to this bug: saltstack/salt#4904

It was introduced in salt 0.15.0.

**Comment by vinitkhandagle** [comment] 2013-05-14 15:04
Thanks .... I should have checked that for the Salt issues. Well will keep an eye on this issue, thanks for the reference of the issue on saltstack as well..

**Comment by akoumjian** [comment] 2013-05-14 15:05
Sorry for the trouble. A fix should be out in the next couple weeks.

**Comment by vinitkhandagle** [comment] 2013-05-14 15:14
Not At all, atleast coz of this I got to interact with you and know how busy guys take time off to help novice like me as well :+1: . Thanks alec for the help and replies. It was the first time I filed an issue.

**Comment by jdelic** [comment] 2013-05-19 14:48
1. This issue is also a duplicate of #76.
2. As a temporary work-around until salt 0.16.0 comes out (https://github.com/saltstack/salt/issues?milestone=36&state=open) you can patch salty-vagrant:

In line 65 of `[vagrant-install-path]/embedded/gems/gems/vagrant-1.2.2/plugins/communicators/ssh/communicator.rb` change

``` ruby
if opts[:error_check] && exit_status != 0
```

to

``` ruby
if opts[:error_check] && exit_status != 0 && exit_status != 2
```

This might not fix every way this bug expresses itself, but it allowed me to continue testing with vagrant without downgrading my salt-master and everything else to 0.14.1.

**Comment by vinitkhandagle** [comment] 2013-05-19 16:26
This work around did work out.... Will wait for 0.16.0 and test it.

Thanks for the work around. Yea the exit status doesn't seem to be different than "2"

**Closed as completed** 2013-05-19 16:26 UTC
